import { v } from "convex/values";
export const buyingPriority = v.union(
  v.literal("cost"),
  v.literal("availability"),
  v.literal("flexible"),
);
export const buyingOption = v.object({
  supplier: v.string(),
  url: v.string(),
  quantity: v.number(),
  unit: v.string(),
  currency: v.string(),
  unitPriceCents: v.number(),
  freightCents: v.number(),
  taxCents: v.number(),
  expectedOn: v.string(),
});

export const chatTask = v.union(
  v.literal("onboarding"),
  v.literal("add_item"),
  v.literal("edit_item"),
  v.literal("stock_update"),
  v.literal("new_buy"),
  v.literal("buy"),
  v.literal("settings"),
  v.literal("receive"),
  v.literal("confirm"),
);
export const draftFields = {
  companyName: v.optional(v.string()),
  shippingAddress: v.optional(v.string()),
  name: v.optional(v.string()),
  sku: v.optional(v.string()),
  unit: v.optional(v.string()),
  stock: v.optional(v.number()),
  dailyUsage: v.optional(v.number()),
  buyingPriority: v.optional(buyingPriority),
  dailyLossCents: v.optional(v.number()),
  lossCurrency: v.optional(v.string()),
  stockoutImpact: v.optional(v.string()),
  leadTimeDays: v.optional(v.number()),
  supplier: v.optional(v.string()),
  buyUrl: v.optional(v.string()),
  supplierEmail: v.optional(v.string()),
  itemId: v.optional(v.id("inventoryItems")),
  quantity: v.optional(v.number()),
  requiredBy: v.optional(v.string()),
  unitPriceCents: v.optional(v.number()),
  freightCents: v.optional(v.number()),
  taxCents: v.optional(v.number()),
  currency: v.optional(v.string()),
  notes: v.optional(v.string()),
  confirmation: v.optional(v.string()),
  expectedOn: v.optional(v.string()),
};
export const deskDraft = v.object(draftFields);

export const questionCode = v.union(
  v.literal("companyName"),
  v.literal("companyWebsite"),
  v.literal("shippingAddress"),
  v.literal("confirmAddress"),
  v.literal("name"),
  v.literal("itemId"),
  v.literal("stock"),
  v.literal("unit"),
  v.literal("dailyUsage"),
  v.literal("buyingPriority"),
  v.literal("dailyLossCents"),
  v.literal("quantity"),
  v.literal("requiredBy"),
  v.literal("unitPriceCents"),
  v.literal("freightCents"),
  v.literal("taxCents"),
  v.literal("currency"),
  v.literal("supplier"),
  v.literal("supplierContact"),
  v.literal("confirmation"),
  v.literal("expectedOn"),
  v.literal("quote"),
  v.literal("ready"),
  v.literal("unsupported"),
  v.literal("noResults"),
);
